// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpjDYChDqIBExVIBZNX2MWaS_ohTAs63w',
    appId: '1:945973811852:web:fd23ef4331666e6f35b9a9',
    messagingSenderId: '945973811852',
    projectId: 'my-book-7d416',
    authDomain: 'my-book-7d416.firebaseapp.com',
    storageBucket: 'my-book-7d416.firebasestorage.app',
    measurementId: 'G-HLQD91CZSH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu9bMpRcx5HFk7qa34cCIzVB89AxawMjM',
    appId: '1:945973811852:android:2b9441129ee3a7f235b9a9',
    messagingSenderId: '945973811852',
    projectId: 'my-book-7d416',
    storageBucket: 'my-book-7d416.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMuzumlPfoNE3Lr0jH43Rfzo6L1ArhEw0',
    appId: '1:945973811852:ios:b9b42816fd5ddb8235b9a9',
    messagingSenderId: '945973811852',
    projectId: 'my-book-7d416',
    storageBucket: 'my-book-7d416.firebasestorage.app',
    iosBundleId: 'com.example.newProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMuzumlPfoNE3Lr0jH43Rfzo6L1ArhEw0',
    appId: '1:945973811852:ios:b9b42816fd5ddb8235b9a9',
    messagingSenderId: '945973811852',
    projectId: 'my-book-7d416',
    storageBucket: 'my-book-7d416.firebasestorage.app',
    iosBundleId: 'com.example.newProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpjDYChDqIBExVIBZNX2MWaS_ohTAs63w',
    appId: '1:945973811852:web:ad2a14c54227592035b9a9',
    messagingSenderId: '945973811852',
    projectId: 'my-book-7d416',
    authDomain: 'my-book-7d416.firebaseapp.com',
    storageBucket: 'my-book-7d416.firebasestorage.app',
    measurementId: 'G-31XXBWLX3D',
  );
}
