import 'package:supabase_flutter/supabase_flutter.dart';
import '../../../../core/error/exceptions.dart';
import '../models/notification_settings_model.dart';

abstract class NotificationRemoteDataSource {
  Future<NotificationSettingsModel> getNotificationSettings();
  Future<NotificationSettingsModel> updateNotificationSettings(bool enabled);
}

class NotificationRemoteDataSourceImpl implements NotificationRemoteDataSource {
  final Supabase supabase;

  NotificationRemoteDataSourceImpl({required this.supabase});

  @override
  Future<NotificationSettingsModel> getNotificationSettings() async {
    try {
      final userId = supabase.client.auth.currentUser?.id;
      if (userId == null) {
        throw ServerException();
      }

      final response = await supabase.client
          .from('notifications')
          .select()
          .eq('user_id', userId)
          .maybeSingle();

      if (response == null) {
        // Create default settings if none exist
        final now = DateTime.now();
        final defaultSettings = NotificationSettingsModel(
          id: '', // Will be auto-generated by Supabase
          userId: userId,
          createdAt: now,
          updatedAt: now,
          notification: true,
        );

        final newSettings = await supabase.client
            .from('notifications')
            .insert(defaultSettings.toJsonForInsert())
            .select()
            .single();

        return NotificationSettingsModel.fromJson(newSettings);
      }

      return NotificationSettingsModel.fromJson(response);
    } catch (e) {
      throw ServerException();
    }
  }

  @override
  Future<NotificationSettingsModel> updateNotificationSettings(
    bool enabled,
  ) async {
    try {
      final userId = supabase.client.auth.currentUser?.id;
      if (userId == null) {
        throw ServerException();
      }

      final response = await supabase.client
          .from('notifications')
          .update({
            'notification': enabled,
            'updated_at': DateTime.now().toIso8601String(),
          })
          .eq('user_id', userId)
          .select()
          .single();

      return NotificationSettingsModel.fromJson(response);
    } catch (e) {
      throw ServerException();
    }
  }
}
